site_name: {{ cookiecutter.__pypi_name | tojson() }}
repo_url: {{ cookiecutter.__clone_url | tojson() }}
repo_name: {{ cookiecutter.__pypi_name | tojson() }}
site_author: "{{ cookiecutter.full_name }} <{{ cookiecutter.email }}>"
copyright: {{ cookiecutter.copyright | tojson() }}

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

nav:
  - Home: index.md
  - Developer Interface: developer_interface.md

theme:
  name: "readthedocs"
  logo: resources/logo.png

plugins:
  - search
  - mkdocstrings:  # https://github.com/mkdocstrings/mkdocstrings
      handlers:
        python:
          options:
            show_signature_annotations: true
            show_root_heading: true
            separate_signature: true
markdown_extensions:
  - pymdownx.snippets: {}
